### ISSUE TITLE
[New Library] Clojure(script) implementation of FSRS v4

### ISSUE THREAD

**Issue by vedang** [open-spaced-repetition/cljc-fsrs#1]
Hello maintainers,

I've created a Clojure(script) implementation of the FSRS v4 algorithm at https://github.com/salher/cljc-fsrs 

I have ported the code at `fsrs4anki` and `go-fsrs` to do this. 

If you could read through the README of the project and check my understanding of the implementation, I would be deeply grateful :)

I'm also happy to move the project here or to add the project under this umbrella if that makes sense. Do let me know!

**Comment by L-M-Sherlock** [comment]
Thanks a lot for your contribution! It's great to see FSRS being implemented in different languages. I appreciate the time and effort you put into this.

I'd be happy to move your project under the open-spaced-repetition organization.

Unfortunately, I'm not well-versed with Clojure, so I might not be able to review the code in-depth. But nonetheless, your project is a valuable addition to our community.

Thanks again for your hard work!

**Comment by vedang** [comment]
Thank you for the invitation. I have moved the repository over to `open-spaced-repetition`. 

Do not review the code, but please read through the README and check if the function names and general output looks right. 

In the Clojure / Java world, the artifact (Jar) is expected to be uploaded to a Central Repository (like Maven, Sonatype, Clojars etc). To upload `com.open-spaced-repetition/cljc-fsrs` to Clojars, the parent group (`com.open-spaced-repetition`) would need to be created and managed. Would you want to do this or should I set it up? I can do the initial setup and artifact upload, and then transfer the credentials to you if you prefer that.

**Comment by L-M-Sherlock** [comment]
https://github.com/open-spaced-repetition/cljc-fsrs/blob/6d79305f2ecf3b08893b05f05e90012a71dcc66c/src/open_spaced_repetition/cljc_fsrs/scheduler.cljc#L146

I think it is inconsistent with the go-fsrs:

https://github.com/open-spaced-repetition/go-fsrs/blob/70232f222d0c0ef7523ffa7ceb3de91feddf6030/fsrs.go#L26

**Comment by vedang** [comment]
> I think it is inconsistent with the go-fsrs:

Yes, that's right. The reason is that I assumed that the `go-fsrs` code base was behind and the `fsrs4anki` code base was the canonical code. So where-ever I found the codebases differing, I preferred the `fsrs4anki` code. In this particular case:
https://github.com/open-spaced-repetition/fsrs4anki/blob/2b64b93ac91a7483c7756a02eff0f4c5472b572c/fsrs4anki_scheduler.js#L115

**Comment by L-M-Sherlock** [comment]
The implementation of FSRS4Anki is incomplete, because it outsources the short-term schedule to Anki's built-in algorithm (learning steps).

**Comment by vedang** [comment]
Okay. The weights and formulae in `go-fsrs` were outdated, so I went with `fsrs4anki`. I will modify the "algorithm" (what happens to the card in each state) to match the code in `go-fsrs`. I'll post an update here once it's done.

**Comment by L-M-Sherlock** [comment]
I will update `go-fsrs` once the FSRS v4 is stable.
